set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/zerotoasic/asic_tools/pdk/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/zerotoasic/asic_tools/pdk/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/i_tree"
set ::env(DESIGN_NAME) "i_tree"
set ::env(VERILOG_FILES) "/openlane/designs/i_tree/src/InputBuffer.v /openlane/designs/i_tree/src/i_tree.v /openlane/designs/i_tree/src/IsolationTreeStateMachine.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10.0"
set ::env(DESIGN_IS_CORE) "1"
